version: "3.7"
services:
  currency-exchange:
    image: guptaj/mm-currency-exchange:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
      MANAGEMENT.OLTP.TRACING.ENDPOINT: http://jaeger-server:4318/v1/traces
    networks:
      - global-network
      
  currency-conversion:
    image: guptaj/mm-currency-conversion:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
    networks:
      - global-network
  api-gateway:
    image: guptaj/mm-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka/
    networks:
      - global-network
  naming-server:
    image: guptaj/mm-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - global-network
  jaeger-server:
    image: jaegertracing/all-in-one:latest
    mem_limit: 700m
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - global-network
#  zipkin-server:
#    image: openzipkin/zipkin:latest
#    mem_limit: 700m
#    ports:
#      - "9411:9411"
#    networks:
#      - global-network
networks:
  global-network: